holder:
  image:
    repository: ghcr.io/usingtechnology/do-app/traction-holder
    pullPolicy: Always
    tag: 48da8b6
verifier:
  image:
    repository: ghcr.io/usingtechnology/do-app/traction-verfier
    pullPolicy: Always
    tag: 48da8b6
