holder:
  image:
    repository: ghcr.io/usingtechnology/do-app/traction-holder
    pullPolicy: Always
    tag: sha-5ede0a5
verifier:
  image:
    repository: ghcr.io/usingtechnology/do-app/traction-verfier
    pullPolicy: Always
    tag: sha-5ede0a5
