holder:
  image:
    repository: ghcr.io/usingtechnology/do-app/traction-holder
    pullPolicy: Always
    tag: ghcr.io/usingtechnology/holder_image:sha-461c7bb
verifier:
  image:
    repository: ghcr.io/usingtechnology/do-app/traction-verfier
    pullPolicy: Always
    tag: ghcr.io/usingtechnology/verifier_image:sha-bc51392
