apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "holder.fullname" . }}
  labels:
    {{- include "holder.labels" . | nindent 4 }}
data:
  IMAGE_TAG: {{ .Values.holder.image.tag | quote }}
  IMAGE_VERSION: {{ .Values.holder.image.version | quote }}
  IMAGE_BUILDTIME: {{ .Values.holder.image.buildtime | quote }}