apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "verifier.fullname" . }}
  labels:
    {{- include "verifier.labels" . | nindent 4 }}
data:
  IMAGE_TAG: {{ .Values.verifier.image.tag | quote }}
  IMAGE_VERSION: {{ .Values.verifier.image.version | quote }}
  IMAGE_BUILDTIME: {{ .Values.verifier.image.buildtime | quote }}