release:
  version: '0.0.1'
holder:
  image:
    tag: "ghcr.io/usingtechnology/holder_image:sha-182fe25"
    version: 'sha-182fe25'
    buildtime: '2021-12-31T20:56:59.417Z'
verifier:
  image:
    tag: "ghcr.io/usingtechnology/verifier_image:sha-182fe25"
    version: 'sha-182fe25'
    buildtime: '2021-12-31T20:56:58.473Z'
